### ISSUE TITLE
Add abrisco/rules_helm to bzlmod

### ISSUE THREAD

**Issue by abrisco** [abrisco/rules_helm#27]
This tracks updating the release process to make sure https://github.com/bazelbuild/bazel-central-registry is up to date.

**Comment by abrisco** [comment]
cc @opicaud I opened https://github.com/bazelbuild/bazel-central-registry/issues/1048 to see what it takes to upload releases to the repository

**Comment by opicaud** [comment]
Hey @abrisco,
Top! I am going to send rules_pact as well, i saw that some few things needs to be done in the repo itself, I will try as well on my side.
Olivier

**Comment by abrisco** [comment]
https://github.com/bazelbuild/bazel-central-registry/pull/1322 should conclude this!
