### ISSUE TITLE
helm push 

### ISSUE THREAD

**Issue by iDiogenes** [abrisco/rules_helm#28]
Hello,

First, thank you for creating this bazel rule for helm; it covers a lot of functionality that I was looking for. However, I do have a question about pushing the chart. I see that the `helm_push` rule pushes images used in the chart, which is fantastic. But what I don't see is a method to push the chart itself to either an OCI registry or ChartMuseum. In the Helm CLI, `helm push` pushes the package to a repository, but I don't see a way to do that within this rule. If you could provide some guidance on this, I would really appreciate it.

Thank you!

**Comment by abrisco** [comment]
Hi! That's definitely an oversight. If you have ideas on how that should be added I'd love to review a PR 😅

**Comment by abrisco** [comment]
Sorry for the delay, this sounds good to me!

**Comment by abrisco** [comment]
Implemented on https://github.com/abrisco/rules_helm/pull/44
