### ISSUE TITLE
Add possibility to push to an helm registry

### ISSUE THREAD

**Issue by opicaud** [abrisco/rules_helm#50]
Hello,

Everything is in the description, today `helm_push_registry` is pushing oci images, I would prefer using `oci_push` for that and use `helm_push_registry` to push helm charts in an helm registry.

Any thoughts about that ?

Olivier

**Comment by abrisco** [comment]
I thought that's how it worked today. Does helm itself push images? I don't think the registrar is explicitly pushing images with `helm_push_registry`.

**Comment by opicaud** [comment]
Indeed! my mistake :)

**Comment by abrisco** [comment]
hehe should this ever regress though I share your preference and would want to correct that 😄
