### ISSUE TITLE
Using build metadata in semantic version of a chart causes packager.go to fail

### ISSUE THREAD

**Issue by cbullo** [abrisco/rules_helm#66]
According to [Build Metadata](https://semver.org/#spec-item-10) it should be possible to use '+' sign to annotate version with build metadata. 
However, the regex [packager.go:500](https://github.com/abrisco/rules_helm/blob/8b5f89988057e54cf395c71c3d05b6e58ed843db/helm/private/packager/packager.go#L500) doesn't allow that.

Using this string as a chart version will fail: `0.0.9+63-gf336c00`.

**Comment by abrisco** [comment]
Uh-oh. I'd be happy to review a change to fix this 😀

**Comment by abrisco** [comment]
This is resolved by https://github.com/abrisco/rules_helm/pull/82
