### ISSUE TITLE
helm_package templates should take a folder

### ISSUE THREAD

**Issue by iDiogenes** [abrisco/rules_helm#69]
Hello!

Currently, `helm_package` templates require a list of all Helm template files. This approach can be problematic when you are trying to merge template files from various parts of your repo that do not match the same folder structure. For example, if I need to build a single chart that has template files in `infra/charts/templates` and `oem/vendor/infra/charts/templates`, I am currently receiving the following error: `packager.go:628: Template path (oem/vendor/infra/charts/templates) does not start with templates root (infra/charts/templates)`.

To fix this, templates should be able to target a folder, and I see two ways to accomplish this:

Option 1) The least destructive method is to update the `installHelmContent` function in `packager.go` to determine if `templatesManifest` is a folder and respond accordingly.

Option 2) Change the `helm_package` templates to be a label that takes a path to the templates directory. This approach is a bit cleaner because it requires the user to ensure that everything is co-located properly in a templates folder when submitting.

I am happy to make the necessary changes as I am currently blocked by this issue, so please let me know your thoughts when you have a moment.

Thank you.

**Comment by abrisco** [comment]
Sorry for the delay here, is https://github.com/abrisco/rules_helm/commit/86b6fd987799c45ee10a2efd7b7e7349de0f0409 the solution for this?

**Comment by iDiogenes** [comment]
@abrisco - Yes it looks like my commit to solve this was merged in, so this can now be closed. Thank you.
